### ISSUE TITLE
Incompatibility with Kubernetes 1.24

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-api#140]
API seems to be incompatible with Kubernetes 1.24.   
This may be solved by upgraded this Kubernetes client dependency, I will test that.

```
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "io.fabric8.kubernetes.api.model.ObjectReference.getName()" is null
	at fr.insee.onyxia.api.services.impl.HelmAppsService.lambda$getServiceFromRelease$13(HelmAppsService.java:296) ~[classes!/:master]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
	at fr.insee.onyxia.api.services.impl.HelmAppsService.getServiceFromRelease(HelmAppsService.java:307) ~[classes!/:master]
	at fr.insee.onyxia.api.services.impl.HelmAppsService.getHelmApp(HelmAppsService.java:209) ~[classes!/:master]
	at fr.insee.onyxia.api.services.impl.HelmAppsService.getUserService(HelmAppsService.java:181) ~[classes!/:master]
	at fr.insee.onyxia.api.services.impl.HelmAppsService$$FastClassBySpringCGLIB$$61c6d9bd.invoke(<generated>) ~[classes!/:master]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar!/:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.18.jar!/:5.3.18]
	at fr.insee.onyxia.api.services.impl.HelmAppsService$$EnhancerBySpringCGLIB$$250e3332.getUserService(<generated>) ~[classes!/:master]
	at fr.insee.onyxia.api.controller.api.mylab.MyLabController.getApp(MyLabController.java:111) ~[classes!/:master]
```

**Comment by olevitt** [comment]
Fixed by #141
